name: shopping_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.1
  flutter_svg: ^2.3.0
  carousel_slider: ^5.1.2
  smooth_page_indicator: ^2.0.1
  readmore: ^3.0.0
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  flutter_bloc: ^9.1.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^6.8.0
  date_format: ^2.0.9
  intl: ^0.20.3
  dio: ^5.11.0
  get_it: ^9.2.1
  google_maps_flutter: ^2.18.0
  geolocator: ^14.0.3
  geocoding: ^4.0.0
  equatable: ^2.1.0
  http: ^1.6.0
  firebase_storage: ^13.5.0
  image_picker: ^1.2.3
  flutter_stripe: ^14.0.0
  shared_preferences: ^2.5.5
  webview_flutter: ^4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
